name: Werewolf
version: '${project.version}'
main: net.tv.twitch.chrono_fish.werewolf.Main
api-version: '1.20'
description: "werewolf v1.0 !!!!!"
commands:
  game:
    permission: "ww.op"
  cpu:
    permission: "ww.op"
  timezone:
    permission: "ww.op"
  role:
    permission: "ww.op"
  action:
    permission: "ww.every"
  ww:
    permission: "ww.op"
permissions:
  ww.op:
    default: op
  ww.every:
    default: true

